### ISSUE TITLE
Error on delete record from DB 

### ISSUE THREAD

**Issue by mgonzalez-msights** [uberllama/s3_direct_upload_example#1]
When I destroy a record from the "Documents" table i get the following error

[AWS S3 404 0.300081 0 retries] head_object(:bucket_name=>"BUCKET",:key=>"APP/MODEL/uploads/ID/original/FILENAME") AWS::S3::Errors::NoSuchKey No Such Key

In S3 I'm saving files using the following path: BUCKET/MODEL/uploads/ID/original/FILENAME

Is it trying to delete the file from s3, but getting the path wrong? Or what's the matter?

here's my initilizer conf for the path:

path: ':class/:attachment/:id/:style/:filename',

**Comment by dja** [comment]
@mgonzalez-msights @uberllama I'm having a similar issue... When an attachment requires post processing, it tries to connect to AWS S3 at the styles paths and errors out.

Here's the error:

```
[AWS S3 404 0.316077 0 retries] head_object(:bucket_name=>"micro-development",:key=>"snaps/attachments/177/original/1 - HelmetSnap.jpg") AWS::S3::Errors::NoSuchKey No Such Key

[AWS S3 404 0.076765 0 retries] head_object(:bucket_name=>"micro-development",:key=>"snaps/attachments/177/iphonejpg/1 - HelmetSnap.jpg") AWS::S3::Errors::NoSuchKey No Such Key

Command :: file -b --mime '/var/folders/xp/x05t0sw92fdcqnk_221t4lcc0000gn/T/4da645c7f7ad527cb92f631fe17535f120140818-6431-zl62c7.jpg'
   (0.2ms)  BEGIN
Command :: file -b --mime '/var/folders/xp/x05t0sw92fdcqnk_221t4lcc0000gn/T/4da645c7f7ad527cb92f631fe17535f120140818-6431-55e0i5.jpg'
   (0.2ms)  ROLLBACK
[AWS S3 204 0.250464 0 retries] delete_object(:bucket_name=>"micro-development",:key=>"uploads/1408417356392-91sab9n2fpv-39eac95fe1c37c024d33e33954615e88/1 - HelmetSnap.jpg")
```

**Comment by dja** [comment]
Nevermind - found that Paperclip with S3 was raising an issue, but Paperclip with S3 through Fog does not.

**Comment by uberllama** [comment]
Interesting. Wonder if there's an issue with a recent version of the paperclip or aws-sdk gem. Wouldn't be the first time.
