### ISSUE TITLE
Wrong content-type set on S3

### ISSUE THREAD

**Issue by dja** [uberllama/s3_direct_upload_example#3]
Hey Yuval,

Did you ever see an issue where the content-type stored on S3 has a comma preceding it? ie. ",image/jpeg" instead of "image/jpeg"?

It's the weirdest thing.. From s3_direct_upload, the filetype returned in javascript is accurate, but what's stored on S3 has the comma.

Any advice would be awesome!

**Comment by uberllama** [comment]
Have never seen that, no.
